# This is a basic workflow to help you get started with Actions

name: Changelog Action
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ release-1.15 ]
    paths-ignore: 
      - '**.md'
  pull_request:
    branches: [ release-1.15 ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@master
        with:
          path: '/root/.gradle/daemon/4.9/Titanium'  
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it   
      - name: Changelog Action
        uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-14
        with:
          args: makeChangelog
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Buuz135
          author_email: changelog@gmail.com
          message: "Updated changelog"
          add: "**.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
